first_name = "Max"
last_name = "Mustermann"
barcode = "12345678-90"
qualified = false
hide_indicator = true
picture = "placeholder.png"
deployment = ["GAGr", "Helferanwärter"]
qualifications = ["Motorsäge A/B"]
licenses = ["KF CE", "Staplerschein"]
